POST http://localhost:8080/channel/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MTAwMjI2LCJleHAiOjE2NzUxMDM4MjZ9.oEB0Hdmex1DzdROXOObsgWh3CS89lKZrivDKMb5gMWdgEe7tWRVqm87J_H5TeZMHlNwCJEk1fcFT3NYXP-KaYw
Content-Type: application/json

{
  "channelName" : "java",
  "description" : "channel for java contents",
  "channelType" : "PRIVATE",
  "chatLink" : ""
}

###

POST http://localhost:8080/channel/broadcast
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MTAwMjI2LCJleHAiOjE2NzUxMDM4MjZ9.oEB0Hdmex1DzdROXOObsgWh3CS89lKZrivDKMb5gMWdgEe7tWRVqm87J_H5TeZMHlNwCJEk1fcFT3NYXP-KaYw
Content-Type: application/json

{
  "channelId" : 1,
  "message" : "Hello Iam owner"
}

###

POST http://localhost:8080/channel/add/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0ODgyNzUxLCJleHAiOjE2NzQ4ODYzNTF9.VaWla49HzlxHWCrB6C4ggi8uW_BGjXbH4dCCQusye61FoUb5CDI7GaLu_1C5qysqDZeqxvEkyc9u2SVlsrFmug
Content-Type: application/json

{
  "channelId" : 1,
  "usernames" : ["josh"]
}

###

POST http://localhost:8080/channel/give/permission
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0ODM1NTAyLCJleHAiOjE2NzQ4MzkxMDJ9.MoGT5kugVQDpq99Njx4UainBd9cTj5SNkECR2sKSx7mIVH0RkOVATvMXDF7N9ps-Rti9lWntxbzAa1m-f7N5-w
Content-Type: application/json

{
  "channelId" : 1,
  "username" : "josh"
}


###

POST http://localhost:8080/channel/remove/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0ODgzOTY2LCJleHAiOjE2NzQ4ODc1NjZ9.Gw1xPBxJp_zwdLEQEFZfyYdA30LJGKX4BgVuXY0_3ESLNFzCKf3b9a7i-tqKI474GULHvVFQzs-p5pvjgf6kCg
Content-Type: application/json

{
  "channelId" : 1,
  "usernames" : ["josh"]
}

###

DELETE http://localhost:8080/channel/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0ODgzOTY2LCJleHAiOjE2NzQ4ODc1NjZ9.Gw1xPBxJp_zwdLEQEFZfyYdA30LJGKX4BgVuXY0_3ESLNFzCKf3b9a7i-tqKI474GULHvVFQzs-p5pvjgf6kCg
Content-Type: application/json


