GET http://localhost:8080/chat/getAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huIiwiaWF0IjoxNjc0NzIzODYwLCJleHAiOjE2NzQ3Mjc0NjB9.McPk6BUvz3PTV698lPKp_kx1qSzw0dhgwdJMX76fTuE-visNTzKnmZFfb8cc78pqpPlHQbftFgCKU6EXK1hxRA
Content-Type: application/json