GET http://localhost:8080/chat/getAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3NoIiwiaWF0IjoxNjc0NjQ0ODQ4LCJleHAiOjE2NzQ2NDg0NDh9.grbAzyN7DXjNVquIjxns0krTOYUfatLsHi63mw8zDibAKT7Jkq0vzUiTUZkrUmculTW0Kh77GO-6hfluQNdwbw
Content-Type: application/json