POST http://localhost:8080/group/set/photo
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MDA2ODYwLCJleHAiOjE2NzUwMTA0NjB9.zNufoXCaSEV2QkthoqI178uNpXBPUAc8S_EHxKapcUSk2E89kx1oxw2z1uFoubO5khRhItHL6YLGWct70bkI6w

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="shopping.jpg"
Content-Disposition: form-data; name="groupId";

< /home/cosmos/WebstormProjects/app1/src/assets/shopping.jpg
groupId-1
--WebAppBoundary--

###
POST http://localhost:8080/group/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MDA2ODYwLCJleHAiOjE2NzUwMTA0NjB9.zNufoXCaSEV2QkthoqI178uNpXBPUAc8S_EHxKapcUSk2E89kx1oxw2z1uFoubO5khRhItHL6YLGWct70bkI6w
Content-Type: application/json

{
  "name" : "Youtube",
  "description" : "best platform for learning",
  "usernames" : ["josh"]
}

###

POST http://localhost:8080/group/add/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0ODg0NDMyLCJleHAiOjE2NzQ4ODgwMzJ9.9YekNCR-aqvM-ESQCLOsXO3w8x95ADnZZzJEl81js_MDXBa2o34tDyMkE3Rl1NGeluPO1kaGzTntd1WeEpvdXA
Content-Type: application/json

{
  "usernames" : ["josh"],
  "chatId" : 1,
  "groupId" : 1
}


###

GET http://localhost:8080/group/leave/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3NoIiwiaWF0IjoxNjc0NzQ5MjE5LCJleHAiOjE2NzQ3NTI4MTl9.NjDlBe7nspuA4iV85fmTiwxYr_U6aGDEcx-P-j7lt5BvFNNKaA6Tknel9Mpc97CNswMw1zpp276U40-37GaGDw
Content-Type: application/json

###

POST http://localhost:8080/group/remove/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY3NDc0MTIzNSwiZXhwIjoxNjc0NzQ0ODM1fQ.gtSOV7jWbl8U6mRrrehgIQgv90dB1_Bg0HUR86E7NzQZeHRySooQCZ9kOWBlp6YyUh6L6g1hqEITiBjVlrKD7w
Content-Type: application/json

{
  "chatId" : 1,
  "usernames" : ["josh"]
}

###

POST http://localhost:8080/group/give/permission
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY3NDc0MTkxMywiZXhwIjoxNjc0NzQ1NTEzfQ.dsnVTS74VauJU2929iO5BMwMWbyi65i4PZH0bb-zA3ADIXBeXkwJd13GyyFnbnIsZOwEaVDC7YOeZeMMB2y27Q
Content-Type: application/json

{
  "groupId" : 2,
  "username" : "josh"
}
###

DELETE http://localhost:8080/group/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0ODgyNzUxLCJleHAiOjE2NzQ4ODYzNTF9.VaWla49HzlxHWCrB6C4ggi8uW_BGjXbH4dCCQusye61FoUb5CDI7GaLu_1C5qysqDZeqxvEkyc9u2SVlsrFmug
Content-Type: application/json
