POST http://localhost:8080/message/upload/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0OTI5MjY0LCJleHAiOjE2NzQ5MzI4NjR9.5RaAcIFOqlxc1v3LsGirANhLqnaQTSazIl4L_Ck_7X36mb97JPzym4Eyn0XMsovhjRX3WaBUoznZTKHMTEA8Iw
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image_2023-01-23_21-14-45.png"

< /home/cosmos/Downloads/Telegram Desktop/image_2023-01-23_21-14-45.png
--WebAppBoundary--

###
GET http://localhost:8080/message/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3NoIiwiaWF0IjoxNjc0NzQ5MjE5LCJleHAiOjE2NzQ3NTI4MTl9.NjDlBe7nspuA4iV85fmTiwxYr_U6aGDEcx-P-j7lt5BvFNNKaA6Tknel9Mpc97CNswMw1zpp276U40-37GaGDw

###

POST http://localhost:8080/message/send
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MDE2NzkyLCJleHAiOjE2NzUwMjAzOTJ9.2mypH0dmmydVETPusnngZoXaRf_gWHRQH8J8X8pazrNd_kHmmf6VyJOhrSpPaJ3ACEcHTLCnMQ0Z6K4go2AQXQ
Content-Type: application/json

{
  "chatId" : 0,
  "message" : "Hello programming is easy.",
  "friendId" : 1
}

###

POST http://localhost:8080/message/edit
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huIiwiaWF0IjoxNjc0NzE2NTIzLCJleHAiOjE2NzQ3MjAxMjN9.nSs85mN57n8y85Z3ULmdmC8tYu1FLccmF_pYSSKr3SnAWIKIzEGcXM6BeHTQe8LihOXOKTuUlQ3DTwwywIamlg
Content-Type: application/json

{
  "message" : "Hi",
  "messageId" : 2
}

###

//eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MDE2MDAwLCJleHAiOjE2NzUwMTk2MDB9.sH-S-1B0ZyDMVrHw3aIYRhgsQqtAsQdlGUzvd0qnTq4WMhqt4ImJXERjB5wx_y78O8Wol8tsGKAi0n4WJsP4qQ

###
POST http://localhost:8080/message/search
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MDE2NzkyLCJleHAiOjE2NzUwMjAzOTJ9.2mypH0dmmydVETPusnngZoXaRf_gWHRQH8J8X8pazrNd_kHmmf6VyJOhrSpPaJ3ACEcHTLCnMQ0Z6K4go2AQXQ
Content-Type: application/json

{
  "message" : "He",
  "chatId" : 2
}

###
POST http://localhost:8080/message/search/date
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc1MDE3MjM2LCJleHAiOjE2NzUwMjA4MzZ9.n3t8ZILiTPF-TJG3ySrNfk0Gmh5iXfuGHMYQDEVlO0XNQW_tHYlOa9KaXPBoPOoZClK5n94RTlrD4e8ltq3TSw
Content-Type: application/json

{
  "message" : "He",
  "chatId" : 2,
  "date" : "2023-01-29"
}
