POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name" : "josh",
  "phoneNumber" : "345673256",
  "username" : "josh",
  "password" : "123"
}

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name" : "test",
  "phoneNumber" : "367282992",
  "username" : "test",
  "password" : "123"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
"username" : "test",
"password" : "123"
}

###

//eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjc0Nzk4OTcwLCJleHAiOjE2NzQ4MDI1NzB9.O-DoAarGBS24SLQi4ivApX2ZVppu-tM48VEKInhuBU4le3EMg18-fcRucstWoYqzd86tV4rpnP2nMDwX02WW7g


GET http://localhost:8080/user/delete
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huIiwiaWF0IjoxNjc0NzE5NTg3LCJleHAiOjE2NzQ3MjMxODd9.CCsBfU9Ov6tkXHbn3KmJSvLC1g7abbJx-cocWB-Z03PutRdj15KAofOce0AmrMteM_e3p04ai9TPHZp0hfrrbQ
Content-Type: application/json
